config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "users/registrations" }

  devise_scope :user do
    authenticated :user do
      root "dashboards#show", as: :authenticated_root
    end

    unauthenticated do
      root "devise/sessions#new", as: :unauthenticated_root
    end
  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "pages#home"

  resources :groups, except: :index do
    # resources :memberships, only: %i[create destroy]
    resources :invitations, only: %i[new create]
  end
  get "join/:token", to: "groups#join", as: "join_group"

  resources :invitations, only: [] do
    member do
      patch "accept"
      patch "decline"
    end
  end

  resources :availabilities, except: %i[index show]

  # resources :memberships, only: [:destroy]
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def show
    @groups = current_user.groups
    @invitations = current_user.invitations.pending
    @availabilities = current_user.availabilities
    authorize :dashboard, :show?
  end
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/views/dashboards/show.html.erb
<div class="container">
  <div class="mt-4">
    <h1>Hi <%= current_user.name %>!</h1>
    <h2>Your Groups</h2>
  </div>

  <% if @groups.any? %>
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Name</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @groups.each do |group| %>
          <tr>
            <td><%= group.name %></td>
            <td>
              <%= link_to 'View', group_path(group), class: "btn btn-info btn-sm" %>
              <% if current_user.id == group.owner_id %>
                <%= link_to 'Edit', edit_group_path(group), class: "btn btn-warning btn-sm" %>
                <%= link_to 'Delete', group_path(group), data: {turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "btn btn-danger btn-sm" %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% else %>
    <p>No groups found. Create one now!</p>
  <% end %>
  <div class="mb-3">
    <%= link_to 'Create New Group', new_group_path, class: "btn btn-primary" %>
  </div>

  <div class="mt-3">
    <h2>Pending Invitations</h2>

    <% if @invitations.any? %>
      <table class="table table-striped">
        <thead>
          <tr>
            <th>Group</th>
            <th>Invited By</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          <% @invitations.each do |invitation| %>
            <tr>
              <td><%= invitation.group.name %></td>
              <td><%= invitation.invited_by.name %></td>
              <td>
                <%= button_to 'Accept', accept_invitation_path(invitation), method: :patch, class: "btn btn-success btn-sm" %>
                <%= button_to 'Decline', decline_invitation_path(invitation), method: :patch, class: "btn btn-danger btn-sm" %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% else %>
      <p>No pending invitations.</p>
    <% end %>
  </div>
  <div class="mt-3">
    <h2>Availability</h2>
    <%= link_to 'Add new availability', new_availability_path, class: "btn btn-primary" %>

    <% if @availabilities.any? %>
      <table class="table table-striped">
        <thead>
          <tr>
            <th>Date</th>
            <!--<th>End Date</th>-->
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          <% @availabilities.each do |availability| %>
            <tr>
              <td><%= availability.start_time.to_date %></td>
              <!--<td><%#= availability.end_time.to_date if availability.end_time %></td>-->
              <td>
                <%= link_to "Edit", edit_availability_path(availability), class: "btn btn-warning btn-sm" %>
                <%= link_to 'Delete', availability_path(availability), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "btn btn-danger btn-sm" %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% else %>
      <p>No availabilities set</p>
    <% end %>
  </div>
</div>